### ISSUE TITLE
Mass save-to-disk

### ISSUE THREAD

**Issue by contrapunctus-1** [openintents/notepad#32]
How may one mass save files to disk, for, say, migrating between phones when one has a lot of files in OI Notepad? Or are there any files in the filesystem one can copy? (I was unable to find any on an unrooted Android v7 phone). I'm using v1.5.4 from F-Droid.

PS - Please consider setting up a chat room for easier communication - preferably XMPP or IRC...

**Comment by aperomsik** [comment]
OI Convert CSV should work for transferring all notes at once. 

That said... when I recently switched phones, I used adb backup instead. For that approach you need a computer with the Android SDK installed -- or at least the adb portion, which I've heard was recently made available separately. 

plug in old phone, then type
```adb backup -f notepad.ab org.openintents.notepad```
Then make sure phone screen is unlocked, and accept the prompt.
When it says it is done, unplug old phone, plug in new phone
```adb restore notepad.ab```
Again make sure phone screen is unlocked, and accept the prompt.

**Comment by contrapunctus-1** [comment]
Thank you! I successfully migrated using OI Convert CSV (I couldn't find it in F-Droid, so had to resort to the Play Store). I tried `adb backup` earlier, but it can't work in my case (moving from Android v7 to v6).
